### ISSUE TITLE
[FEATURE] Sort the episode list on the release dates (newer releases first)

### ISSUE THREAD

**Issue by jcompagner** [robvdpol/RaceControl#106]
if i go to for example archive -> jolyon then that list that is shown in the episodes are for me a bit random
I expect that the latest video's are at the top (of the bottom if you want to make it configurable)
(tech talk is the same also a bit random)

the race itself seems ok, but i like to have te newest one first not the other way around.

**Comment by billbatista** [comment]
It seems here that not all videos from the "Archive" category have a `SessionIndex `or `StartDate `values, some have both, some have none and some have either one of the values. I'm not sure what would be the best approach here since I don't have much familiarity with the project and F1's data.
In this particular case the ordering is being done by `SessionIndex`, maybe use StartDate since it's more accurate and to at least have some order.

**Comment by mufraver2** [comment]
There is a `ContractStartDate` property in the `Metadata` object and it seems to work for ordering with the newest episodes at the top. 

Current: 
![image](https://user-images.githubusercontent.com/45003186/116907996-0e74ea80-ac4b-11eb-8b22-fee63743f1be.png)

Order by `ContractStartDate`:
![image](https://user-images.githubusercontent.com/45003186/116908046-1df43380-ac4b-11eb-8ac7-384cdb478353.png)
![image](https://user-images.githubusercontent.com/45003186/116908065-23ea1480-ac4b-11eb-9ba9-af7e871084bb.png)
![image](https://user-images.githubusercontent.com/45003186/116908086-29475f00-ac4b-11eb-8c35-cbd8b13e8217.png)

**Comment by robvdpol** [comment]
I implemented @mufraver2's solution for the episode sorting of the archive section.

The data that we get from the API is a big mess and often incomplete. So there's not really one reliable way of sorting episodes in all circumstances.
