### ISSUE TITLE
[BUG] audio delayed by 5-7 second on live streams (on v1.8)

### ISSUE THREAD

**Issue by telelisast** [robvdpol/RaceControl#11]
As described in title audio is delayed by 5-7 second on live streams in vlc and internal player. Audio is synced in MPV. This happened in previous versions as well sometimes, but mostly in internal player, VLC was fine. Now its also in vlc in 1.8. Makes it unwatchable really.

**Comment by robvdpol** [comment]
This was already an issue before, nothing has changed in 1.8 that could make this problem worse. It's a VLC bug and there's not much I can do about it, other than reporting it to Videolan. Usually closing and re-opening the stream fixes the audio sync. When a stream is in sync it will stay in sync for the whole session (as far as I can tell).

Currently I would recommend using MPV, especially because since version 1.8 you can open your layout in MPV.

**Comment by telelisast** [comment]
I must have been lucky with VLC in previous version then to not come across it. Could be. Using mpv now.

**Comment by robvdpol** [comment]
Should be fixed with the new API and streaming platform. Streamlink integration has also been removed.
