### ISSUE TITLE
[FEATURE] MPC-HC

### ISSUE THREAD

**Issue by snowice0** [robvdpol/RaceControl#114]
I was wondering if you could add player support for HPC-HC with potentially syncing videos across players if possible; streaming with a token is no issue and the player is quite comfortable but maybe enhanced built-in support would be possible. Regards

**Comment by robvdpol** [comment]
Is MPC-HC still under development? I thought it was kind of abandoned and 'replaced' by MPC-BE.

But, yes I can add support for either MPC-HC and/or MPC-BE. However, I will need to do some work on the GUI because the amount of buttons will become a bit much.

Do you know whether MPC-HC/MPC-BE has an option to pass the desired window position and size as a command-line parameter? If it does I can also add layout support to it (similar to MPV).

**Comment by reacap** [comment]
MPC-HC abandoned  , MPC-BE is a way to go at the moment 
Regarding command-line parameter's just try to search or ask [here](https://sourceforge.net/p/mpcbe/tickets/) if needed

**Comment by snowice0** [comment]
I guess I will go ahead an install MPC-BE. Thanks for the heads up - didn't notice and thanks for the heads up

**Comment by robvdpol** [comment]
I did some testing, but MPC-BE doesn't support the F1TV streams, so I added support for MPC-HC instead. MPC-HC is still being maintained by [clsid2](https://github.com/clsid2/mpc-hc). Support for saved layout doesn't seem possible because the commandline parameters don't allow me to specify a window size and location. Also, if you want to open multiple instances of MPC-HC for different streams, you have to check the option 'Open a new player for each media file played' in MPC-HC option menu.
