### ISSUE TITLE
Add 1970-1980 Season reviews

### ISSUE THREAD

**Issue by steph09** [robvdpol/RaceControl#129]
Just wondering if it would be possible to add access to the reviews that are available from 1970-1980. Right now the archive section of the app only goes down to 1981.

https://f1tv.formula1.com/collection/1533/1979-1970/pageID/493_76
https://f1tv.formula1.com/detail/1000003789/1980-season-review

Thanks.

**Comment by robvdpol** [comment]
Will look into it, but can't promise anything. The current API is awful to use in a generic way.

**Comment by mufraver2** [comment]
@robvdpol 

I was able to show those by adding a new genre manually.
![image](https://user-images.githubusercontent.com/45003186/118702411-8f241100-b81d-11eb-88b9-295f171f5a67.png)

Also I had to add "FORMULA 1" to the SeriesUID property because it was empty for those. This might not be a good solution but it works as long as the user has "Formula 1" in the Series filtering
![image](https://user-images.githubusercontent.com/45003186/118702647-db6f5100-b81d-11eb-87b8-1c06ec5cc455.png)

And of course the `.OrderByDescending(e => e.ContractStartDate)` doesn't work anymore for that genre
![image](https://user-images.githubusercontent.com/45003186/118703054-57699900-b81e-11eb-95fe-29bda6400f8e.png)

**Comment by robvdpol** [comment]
Good catch about the seriesUID, I changed it so the episodes with empty seriesUID are always shown regardless of checked series.

I also managed to add some more stuff (including season reviews) to the archive by querying different pages. This should do for now.
