### ISSUE TITLE
[FEATURE] Race Seasons older than 2018

### ISSUE THREAD

**Issue by dominikpflegerl** [robvdpol/RaceControl#14]
I'd love to have older seasons showing up in the list. I'm currently rewatching from 2014 onwards, and I'd rather want to watch via Race Control than F1TV as the website kind of slows down my computer while playing a game simultaneously and often the audio is low quality.

Thanks! :-)

**Comment by robvdpol** [comment]
Race seasons before 2018 were not broadcasted live through F1TV, because F1TV didn't exist at the time. However, they can be found in the Video On Demand archive. Simply select the entry called 'Full Race' under 'Video On Demand' and then scroll down the episode list to find the races you want to watch.

![Untitled](https://user-images.githubusercontent.com/56960828/94806327-0d968480-03ee-11eb-93d6-ac5d8e31cb1e.png)
