### ISSUE TITLE
[FEATURE]Installer keeps Install Direction for Updates

### ISSUE THREAD

**Issue by ColeTrickIe** [robvdpol/RaceControl#145]
Would be just a little nice feature if the installer could get the actual install directory if it's not the standard C:\ path when installing a updated version. Think it is a bit of an industry standard but of course more of a fix for beeing too lazy to change the directory manually :) 
Maybe there is already plans for a internal updater which can download updates and install them automatically/with the press of one button?

**Comment by robvdpol** [comment]
I've looked into this before but it's a lot of work for such a minor improvement.

In your case I would recommend installing the Microsoft Store version, it will automatically update to the latest version in the background.

The MSI release is only still there because apparently people use it, otherwise I would have removed it by now :)
