### ISSUE TITLE
Manual adjust synced MPV Windows

### ISSUE THREAD

**Issue by rickschwarz** [robvdpol/RaceControl#147]
Today i tested the Great new sync mpv players.

Realy great but i was wondering the following:

After the opend windows are synced they still gave an aorox. 0.5 sec difference to each other 

Is  it possible to switch of the sync routine in all opend windows by unchecking the mpv sync checkbox so you can manualy adjust those windows that are not completely in sync.

Now when i adjust manualy the sync routine overides my adjustment 

When i unchek the sync checkbox it does not diables the sync routine.

**Comment by rickschwarz** [comment]
Just found out that SHIFT +A disables autosync per open mov player window !!!

Now it's op oerfect !!!!

What a great engancement !!!!

**Comment by rickschwarz** [comment]
Mpv player

**Comment by robvdpol** [comment]
You can also use '(' and ')' to delay/advance playback by 0.1 seconds increments.

**Comment by xantrk** [comment]
Bumping this up since internal player sync while live appears to be broken. 

MPV does a good job syncing internally, but I also want to delay them all to sync it with main feed in my TV (which is using a tv app). Is this possible with disabling one window with SHİFT+A pausing it a few seconds and resuming, will the other tabs keep in sync with the ? How can I achieve this?
