### ISSUE TITLE
[Suggestion] Don't use the "New live session detected" voice line without some system notification/pop-up

### ISSUE THREAD

**Issue by Czorio** [robvdpol/RaceControl#162]
**Is your feature request related to a problem? Please describe.**
I had RaceControl opened in the background after watching FP3, waiting for Qualifying to start, when I suddenly heard a female voice tell me that a new live session was detected.
There is no other indication that this sound came from RaceControl, so my initial response was to look for some form of malware or other running software that would do this, because as far as I knew, something on my machine just connected with something I was not in control of.
It's only through a lucky Google search hit that I realized this was not a virus, but RaceControl.

**Describe the solution you'd like**
I'd much rather see RaceControl make use of the Windows notifications for this purpose, this already provides a visual and audible signal for the user.
If the voice line must stay, make sure that there's at least _some_ indication as to where it came from, either through a notification, or using the functionality that makes programs blink orange in the taskbar.

**Comment by Yesat** [comment]
@robvdpol  mentionned in the suggestion that the notification is a mess due to the different ways it's implemented in Windows.
https://github.com/robvdpol/RaceControl/issues/137#issuecomment-846538987

Personally I'd love to have simply a way to turn it on or off, which I don't seem to be able to do in the settings. Ideally even per series or sessions, but that's superflous. On race weekend, I tend to have the app still running for most of the day and it always startle me, especially as I don't expect F3.

**Comment by robvdpol** [comment]
I added a checkbox to disable the notification sound. As mentioned, Windows notifications are very messy to implement.
