### ISSUE TITLE
[QUESTION] Is the default install folder correct?

### ISSUE THREAD

**Issue by mfkl** [robvdpol/RaceControl#19]
When running the default MSI from releases, the default install folder location is `C:\Race Control\`. 

Is that correct? My guess would be Program Files would be the recommended location.

**Comment by robvdpol** [comment]
The default install folder is a deliberate choice, since folders inside Program Files are read only. Streamlink is a Python application that creates all kinds of cache files, so it's better to not install it in Program Files. Hopefully I can remove the Streamlink dependency soon, then I will also change the install location to Program Files again.
