### ISSUE TITLE
[IMPROVEMENT] UX for close window button of the player

### ISSUE THREAD

**Issue by mfkl** [robvdpol/RaceControl#20]
A UX suggestion.
![close-window](https://user-images.githubusercontent.com/3928834/97135525-14ad7a00-1783-11eb-9dd2-d8b1054353ef.PNG)
These buttons are all very handy, but I'd put the closing button somewhere else:
- You might inadvertently close the window when clicking on other options, since they are pretty closely displayed.
- People are used to having the close button at the top left/right, but I guess you want to keep a no title bar design. Maybe a background-less X that would appear over the video could be an option? Don't know.

Just some first impression feedback, feel free to close this :)

**Comment by bossanovaorca** [comment]
to add onto this, it seems that since the title bars were removed from the external mpv windows, it became impossible for me to use <kbd>Win</kbd> + arrow keys to snap the player window to edges of my monitors. would it be possible to bring back title bars on mpv player windows (maybe as an option)?

**Comment by robvdpol** [comment]
I added a checkbox to disable MPV borderless mode. It still plays nicely with loading of layouts, so that's good.

**Comment by robvdpol** [comment]
I rarely use the close button since pressing the escape button also works. I just added a shortcut to close all player windows using shift + escape. Will close this issue for now.
