### ISSUE TITLE
[BUG] racecontrol marked as virus.

### ISSUE THREAD

**Issue by JvDrunen** [robvdpol/RaceControl#245]
**Describe the bug**
windows defender marks racecontrol.exe as a virus:
Behavior:Win32/SuspVaultEnumerate.C!cl

**To Reproduce**
download portable version (2.4.1)
start
defender blocks the execution after a minute

**Expected behavior**
no virus message

**Screenshots**
![image](https://user-images.githubusercontent.com/30151600/138338117-12620be9-1e3d-43be-b3fd-1d41059a71be.png)

**Desktop (please complete the following information):**
 - Windows 10 / 11 
 - System type (64 bit)
- last test with: 10.0.22000.258

**Comment by RickyNotaro** [comment]
![image](https://user-images.githubusercontent.com/6414422/140826389-3a6c5a04-36f0-4da6-840f-457970a60c21.png)

There's almost nothing on the internet about SuspVaultEnumerate, that will be fun to debug. :')

**Comment by robvdpol** [comment]
Yeah, I don't think I can do much about it.

**Comment by Arcegis** [comment]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Behavior:Win32/SuspVaultEnumerate.C!cl&ThreatID=2147769671

Hello ! Given the info that is written on this link, it might mean that Windows Defender has not gotten enough information about this executable, and, as it is furthermore unsigned, is "framing" it and removing it from the system out of an abundance of caution. I suggest that some of us keep executing RaceControl's various .exe files, so that Defender gathers enough data to consider that RaceControl.exe is not a harmful executable file ?

**Comment by G0lfH0t3l** [comment]
Not sure of this is relevant / the correct "discussion" but this morning I got this notification from ESET Internet Security.
Offcourse I did not capture it but the original notification was triggered but something called "MS Telemetry".

When I access the program folder with Windows file explorer I get an almost identical notification as the first notification:

![racecontrol-01](https://user-images.githubusercontent.com/98510733/151302195-9ae221b4-7bc0-42f4-8165-d6b4e9992c6e.png)

(Something about AtlasVPN.A)

My OS:
Microsoft Windows 10 Pro - 10.0.19042 N/A Build 19042

From my I head I am not on the latest version of the RaceControl MSI
Last modification date of RaceControl.exe is 20 October 2021
