### ISSUE TITLE
[Bug] When opening saved layout drivers onboard also broadcast world feed audio

### ISSUE THREAD

**Issue by DjDaan111** [robvdpol/RaceControl#267]
Describe the bug
I have version 2.5.2 with a saved layout across 2 screens: main screen: Pitlane channel, 2nd screen: Timing, track, Verstappen and Hamilton. 

When I open the saved layout during a live session the 2 driver cams report as teamradio only but I still hear the main broadcast added to it. When I saved this layout I could only hear the teamradio. 

When i close and reopen the 2 driver cams I hear only the teamradio as expected.

To Reproduce

    Open saved player layout (config attached)

Expected behavior
On the 2 driver cams only the teamradio audio.

Screenshots

Desktop (please complete the following information):

    Windows 10 21H1 64 bit
    Version 2.5.2

F1TV account

    F1TV Pro
    Country: NL
    Using VPN or proxy? No

Additional context
Add any other context about the problem here
[RaceControl.layout.txt](https://github.com/robvdpol/RaceControl/files/7545013/RaceControl.layout.txt)
.

**Comment by robvdpol** [comment]
I think this was caused by F1TV renaming the team radio audio streams from 'obc' to 'teamradio'. You can fix this by opening your layout file in a text editor and replace:

`"AudioTrack": "obc"`

by this:

`"AudioTrack": "teamradio"`

Alternatively, you can simply recreate and save your layout using the app.

**Comment by DjDaan111** [comment]
Thanks that fixed the issue!
