### ISSUE TITLE
[FEATURE] All Archive Race Seasons?

### ISSUE THREAD

**Issue by pshankland** [robvdpol/RaceControl#27]
Hoping that all archived seasons will be available for the app rather than just 2018 --> 2020?

**Comment by robvdpol** [comment]
See answer to issue https://github.com/robvdpol/RaceControl/issues/14:

_Race seasons before 2018 were not broadcasted live through F1TV, because F1TV didn't exist at the time. However, they can be found in the Video On Demand archive. Simply select the entry called 'Full Race' under 'Video On Demand' and then scroll down the episode list to find the races you want to watch._

I will add a FAQ entry for this question.

**Comment by robvdpol** [comment]
https://github.com/robvdpol/RaceControl/commit/010adb9cb9533aa95f62ca9544e24bad4acf30a3
