### ISSUE TITLE
[BUG] Default language should not be zxx

### ISSUE THREAD

**Issue by c0nfu** [robvdpol/RaceControl#344]
Hi,

when I download a race onto my computer and open it with VLC player, or on my TV, the default audio option is always "zxx", meaning pure sound without any commentary, despite the Default Audio Language being set to English. I always need to click on Audio in the VLC player and change it to audio track 2 which then contains the English commentary. This is for all videos. Is this a bug? Can it be fixed so that when you set English as default language and open the video, then the English commentary is activated by default?
Thank you!

**Comment by c0nfu** [comment]
I just tested it with the new version 2.6, the issue is the same. I select English als Default language and then download a file, for example 1997 In Review: Australian Grand Prix, and when I open it with VLC the default audio track is the one without any commentary, just ambient sound. I need to click on Audio and manually select Audio Track 2 which contains the commentary.

**Comment by c0nfu** [comment]
@robvdpol Hi sorry to bother you, could you please also check this issue? Or should I open a new thread as this is more a bug than an implementation request? Thanks!

**Comment by Spexxel** [comment]
When downloading a file Race Control does not specify which audio track to download or which one to use when the file opens. All it does is get the file/stream as F1TV provides with all available audio tracks for it. 

When you open the downloaded file VLC knows nothing about the settting in RaceControl since the file wasnt opened through RC, which means VLC will use the default audio track. Which means this is not a bug in RaceControl.

Though you could try setting the "Preferred Audio Language" or default track number within VLC. https://www.wikihow.com/Set-the-Default-Audio-Track-in-VLC

Also, as far as I can see in the code (and from some quick testing) the "default audio language" is only used when watching streams with the built-in player, MPV or when casting.

**Comment by robvdpol** [comment]
As @Spexxel said, there's not much that can be done about this. It's VLC that determines which audio track it opens by default, so I would recommend looking into VLC settings to try to fix that.

Also, as far as I'm know VLC doesn't have a command line parameter to select the audio track, that's why Race Control doesn't support the preferred audio language for VLC.
